[workspace]
resolver = "2"
members = ["crates/nix-manager-core"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://codeberg.org/caniko/nix-manager-core"
authors = ["caniko"]

[workspace.dependencies]
anyhow = "1"
console = "0.15"
dialoguer = "0.11"
indicatif = "0.17"
tempfile = "3"
forgejo-api = { version = "0.10", default-features = false, features = ["sync", "rustls-tls"] }
url = "2"

[workspace.metadata.crane]
name = "nix-manager-core"

[profile.release]
lto = true
strip = true
