[ci]
runner = "codefloe-global"
step_runners = { cargo-clippy = "codeberg-small", cargo-doc = "codeberg-small", cargo-fmt = "codeberg-tiny", cargo-package = "codeberg-medium", cargo-test = "codeberg-medium", quality-tools = "codeberg-small" }
provider = "crow"
platform = "forgejo"
