[package]
name = "nix-manager-core"
description = "Support library for manager-flake Rust projects: ui, exec, repo, age, forge, health, parallel"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "nix_manager_core"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
console.workspace = true
dialoguer.workspace = true
hostname.workspace = true
indicatif.workspace = true
serde.workspace = true
serde_json.workspace = true
forgejo-api.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true
